// This file is auto-generated by @hey-api/openapi-ts

import { type _JSONValue, defineQueryOptions, type UseMutationOptions } from '@pinia/colada';

import { serializeQueryKeyValue } from '../client';
import { client } from '../client.gen';
import { createMyPeer, createPlan, createUser, deleteAdminPeer, deleteMyPeer, deletePlan, deleteSubscription, exchangeTelegramLoginCode, getMe, getMyPeerByDevice, getMyPeerConfig, getMyPeers, getPublicConfig, getStats, getUser, getVersion, listPeers, listPlans, listUsers, type Options, removePeer, sendMyPeerConfig, setSubscription, startTelegramDeepLinkLogin, telegramDeepLinkCallback, telegramLogin, telegramMiniAppAuth, updatePlan } from '../sdk.gen';
import type { CreateMyPeerData, CreateMyPeerResponse, CreatePlanData, CreatePlanResponse, CreateUserData, CreateUserResponse2, DeleteAdminPeerData, DeleteMyPeerData, DeletePlanData, DeletePlanResponse, DeleteSubscriptionData, ExchangeTelegramLoginCodeData, ExchangeTelegramLoginCodeResponse, GetMeData, GetMyPeerByDeviceData, GetMyPeerConfigData, GetMyPeersData, GetPublicConfigData, GetStatsData, GetUserData, GetVersionData, ListPeersData, ListPlansData, ListUsersData, RemovePeerData, SendMyPeerConfigData, SetSubscriptionData, StartTelegramDeepLinkLoginData, TelegramDeepLinkCallbackData, TelegramLoginData, TelegramLoginResponse, TelegramMiniAppAuthData, TelegramMiniAppAuthResponse, UpdatePlanData, UpdatePlanResponse } from '../types.gen';

/**
 * Authenticate via Telegram Login Widget
 */
export const telegramLoginMutation = (options?: Partial<Options<TelegramLoginData>>): UseMutationOptions<TelegramLoginResponse, Options<TelegramLoginData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await telegramLogin({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'path'> & {
        _id: string;
        baseUrl?: _JSONValue;
        body?: _JSONValue;
        query?: _JSONValue;
        tags?: _JSONValue;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (tags) {
        params.tags = tags as unknown as _JSONValue;
    }
    if (options?.body !== undefined) {
        const normalizedBody = serializeQueryKeyValue(options.body);
        if (normalizedBody !== undefined) {
            params.body = normalizedBody;
        }
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query !== undefined) {
        const normalizedQuery = serializeQueryKeyValue(options.query);
        if (normalizedQuery !== undefined) {
            params.query = normalizedQuery;
        }
    }
    return [params];
};

export const telegramDeepLinkCallbackQueryKey = (options?: Options<TelegramDeepLinkCallbackData>) => createQueryKey('telegramDeepLinkCallback', options);

/**
 * Telegram widget callback for deep-link flow.
 */
export const telegramDeepLinkCallbackQuery = defineQueryOptions((options?: Options<TelegramDeepLinkCallbackData>) => ({
    key: telegramDeepLinkCallbackQueryKey(options),
    query: async (context) => {
        const { data } = await telegramDeepLinkCallback({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Exchange one-time login code for JWT + user payload.
 */
export const exchangeTelegramLoginCodeMutation = (options?: Partial<Options<ExchangeTelegramLoginCodeData>>): UseMutationOptions<ExchangeTelegramLoginCodeResponse, Options<ExchangeTelegramLoginCodeData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await exchangeTelegramLoginCode({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Authenticate via Telegram Mini App initData
 */
export const telegramMiniAppAuthMutation = (options?: Partial<Options<TelegramMiniAppAuthData>>): UseMutationOptions<TelegramMiniAppAuthResponse, Options<TelegramMiniAppAuthData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await telegramMiniAppAuth({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const startTelegramDeepLinkLoginQueryKey = (options: Options<StartTelegramDeepLinkLoginData>) => createQueryKey('startTelegramDeepLinkLogin', options);

/**
 * Render the Telegram login page for deep-link flow.
 */
export const startTelegramDeepLinkLoginQuery = defineQueryOptions((options: Options<StartTelegramDeepLinkLoginData>) => ({
    key: startTelegramDeepLinkLoginQueryKey(options),
    query: async (context) => {
        const { data } = await startTelegramDeepLinkLogin({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getPublicConfigQueryKey = (options?: Options<GetPublicConfigData>) => createQueryKey('getPublicConfig', options);

/**
 * Get public configuration
 */
export const getPublicConfigQuery = defineQueryOptions((options?: Options<GetPublicConfigData>) => ({
    key: getPublicConfigQueryKey(options),
    query: async (context) => {
        const { data } = await getPublicConfig({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getMeQueryKey = (options?: Options<GetMeData>) => createQueryKey('getMe', options);

/**
 * Get current authenticated user info
 */
export const getMeQuery = defineQueryOptions((options?: Options<GetMeData>) => ({
    key: getMeQueryKey(options),
    query: async (context) => {
        const { data } = await getMe({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const getMyPeersQueryKey = (options?: Options<GetMyPeersData>) => createQueryKey('getMyPeers', options);

/**
 * List current user's peers
 */
export const getMyPeersQuery = defineQueryOptions((options?: Options<GetMyPeersData>) => ({
    key: getMyPeersQueryKey(options),
    query: async (context) => {
        const { data } = await getMyPeers({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Create a new WireGuard peer for the current user
 */
export const createMyPeerMutation = (options?: Partial<Options<CreateMyPeerData>>): UseMutationOptions<CreateMyPeerResponse, Options<CreateMyPeerData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await createMyPeer({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getMyPeerByDeviceQueryKey = (options: Options<GetMyPeerByDeviceData>) => createQueryKey('getMyPeerByDevice', options);

/**
 * Get a peer by device_id for the current user
 */
export const getMyPeerByDeviceQuery = defineQueryOptions((options: Options<GetMyPeerByDeviceData>) => ({
    key: getMyPeerByDeviceQueryKey(options),
    query: async (context) => {
        const { data } = await getMyPeerByDevice({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Delete a peer owned by the current user
 */
export const deleteMyPeerMutation = (options?: Partial<Options<DeleteMyPeerData>>): UseMutationOptions<unknown, Options<DeleteMyPeerData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteMyPeer({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getMyPeerConfigQueryKey = (options: Options<GetMyPeerConfigData>) => createQueryKey('getMyPeerConfig', options);

/**
 * Get WireGuard config for a peer owned by the current user
 */
export const getMyPeerConfigQuery = defineQueryOptions((options: Options<GetMyPeerConfigData>) => ({
    key: getMyPeerConfigQueryKey(options),
    query: async (context) => {
        const { data } = await getMyPeerConfig({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Send WireGuard config to user via Telegram bot
 */
export const sendMyPeerConfigMutation = (options?: Partial<Options<SendMyPeerConfigData>>): UseMutationOptions<unknown, Options<SendMyPeerConfigData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await sendMyPeerConfig({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const listPeersQueryKey = (options?: Options<ListPeersData>) => createQueryKey('listPeers', options);

/**
 * List all peers (admin only)
 */
export const listPeersQuery = defineQueryOptions((options?: Options<ListPeersData>) => ({
    key: listPeersQueryKey(options),
    query: async (context) => {
        const { data } = await listPeers({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Delete a peer by ID (admin only)
 */
export const deleteAdminPeerMutation = (options?: Partial<Options<DeleteAdminPeerData>>): UseMutationOptions<unknown, Options<DeleteAdminPeerData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteAdminPeer({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const listPlansQueryKey = (options?: Options<ListPlansData>) => createQueryKey('listPlans', options);

/**
 * List all plans (admin only)
 */
export const listPlansQuery = defineQueryOptions((options?: Options<ListPlansData>) => ({
    key: listPlansQueryKey(options),
    query: async (context) => {
        const { data } = await listPlans({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Create a new plan (admin only)
 */
export const createPlanMutation = (options?: Partial<Options<CreatePlanData>>): UseMutationOptions<CreatePlanResponse, Options<CreatePlanData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await createPlan({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Delete a plan (admin only). Fails if plan has subscriptions.
 */
export const deletePlanMutation = (options?: Partial<Options<DeletePlanData>>): UseMutationOptions<DeletePlanResponse, Options<DeletePlanData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deletePlan({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Update a plan (admin only)
 */
export const updatePlanMutation = (options?: Partial<Options<UpdatePlanData>>): UseMutationOptions<UpdatePlanResponse, Options<UpdatePlanData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await updatePlan({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getStatsQueryKey = (options?: Options<GetStatsData>) => createQueryKey('getStats', options);

/**
 * Get system statistics (admin only)
 */
export const getStatsQuery = defineQueryOptions((options?: Options<GetStatsData>) => ({
    key: getStatsQueryKey(options),
    query: async (context) => {
        const { data } = await getStats({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

export const listUsersQueryKey = (options?: Options<ListUsersData>) => createQueryKey('listUsers', options);

/**
 * List all users (admin only)
 */
export const listUsersQuery = defineQueryOptions((options?: Options<ListUsersData>) => ({
    key: listUsersQueryKey(options),
    query: async (context) => {
        const { data } = await listUsers({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Pre-register a user by telegram_id and assign a subscription (admin only).
 * When the user later authenticates via Telegram, their account and subscription will be waiting.
 */
export const createUserMutation = (options?: Partial<Options<CreateUserData>>): UseMutationOptions<CreateUserResponse2, Options<CreateUserData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await createUser({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getUserQueryKey = (options: Options<GetUserData>) => createQueryKey('getUser', options);

/**
 * Get user details (admin only)
 */
export const getUserQuery = defineQueryOptions((options: Options<GetUserData>) => ({
    key: getUserQueryKey(options),
    query: async (context) => {
        const { data } = await getUser({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));

/**
 * Remove all active peers for a user (admin only)
 */
export const removePeerMutation = (options?: Partial<Options<RemovePeerData>>): UseMutationOptions<unknown, Options<RemovePeerData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await removePeer({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Delete (expire) a user's active subscription (admin only)
 */
export const deleteSubscriptionMutation = (options?: Partial<Options<DeleteSubscriptionData>>): UseMutationOptions<unknown, Options<DeleteSubscriptionData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await deleteSubscription({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

/**
 * Set (create or replace) a user's subscription (admin only).
 * If the user already has an active subscription, it will be expired first.
 */
export const setSubscriptionMutation = (options?: Partial<Options<SetSubscriptionData>>): UseMutationOptions<unknown, Options<SetSubscriptionData>, Error> => ({
    mutation: async (vars) => {
        const { data } = await setSubscription({
            ...options,
            ...vars,
            throwOnError: true
        });
        return data;
    }
});

export const getVersionQueryKey = (options?: Options<GetVersionData>) => createQueryKey('getVersion', options);

export const getVersionQuery = defineQueryOptions((options?: Options<GetVersionData>) => ({
    key: getVersionQueryKey(options),
    query: async (context) => {
        const { data } = await getVersion({
            ...options,
            ...context,
            throwOnError: true
        });
        return data;
    }
}));
