/* eslint-disable */
// @ts-nocheck
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Get the persistent device ID.
	 *  Android: ANDROID_ID (stable across reinstalls, per signing key).
	 *  Desktop: random UUID persisted in config dir.
	 */
	getDeviceId: () => typedError<string, string>(__TAURI_INVOKE("get_device_id")),
	/**  Get the device name (Android: manufacturer+model, desktop: hostname) */
	getDeviceName: () => __TAURI_INVOKE<string>("get_device_name"),
	/**
	 *  Ask for a tunnel.
	 * 
	 *  Returns as soon as the actor accepts the intent — the epoch it returns identifies this request
	 *  for [`tunnel_await_cycle`]. There is deliberately no "busy" failure: with a single owner and a
	 *  write-only intent queue, there is no bad moment to ask.
	 */
	tunnelSetIntentUp: (order: Protocol[], params: TunnelParams) => typedError<IntentAccepted, IntentError>(__TAURI_INVOKE("tunnel_set_intent_up", { order, params })),
	/**
	 *  Ask for no tunnel. Also the cancel button: an intent change is how an in-flight attempt is
	 *  stopped.
	 */
	tunnelSetIntentDown: () => typedError<IntentAccepted, IntentError>(__TAURI_INVOKE("tunnel_set_intent_down")),
	/**
	 *  Wait for a request to reach a terminal outcome.
	 * 
	 *  Safe to drop: dropping the future only discards the answer, it never cancels what the actor is
	 *  doing. A caller that asks after the fact still gets the answer, because recent outcomes are
	 *  retained.
	 */
	tunnelAwaitCycle: (epoch: IntentEpoch) => typedError<CycleOutcome, IntentError>(__TAURI_INVOKE("tunnel_await_cycle", { epoch })),
	/**  The current snapshot. A local read of the published state — no IPC, no lock. */
	tunnelGetState: () => __TAURI_INVOKE<TunnelState>("tunnel_get_state"),
	/**
	 *  Store a config under its own protocol key.
	 * 
	 *  Storing is not choosing: this does not change which protocol the next connect would use. The
	 *  previous behaviour of switching to whatever was imported last is what let a server sync
	 *  silently reorder the user's preference.
	 */
	importConfig: (raw: string) => typedError<Protocol, ConfigError>(__TAURI_INVOKE("import_config", { raw })),
	/**
	 *  Forget every stored config.
	 * 
	 *  Goes down and waits for the tunnel to actually be gone before wiping, rather than deciding from
	 *  a status snapshot — which is how a live adopted tunnel could survive being forgotten.
	 */
	clearConfigs: () => typedError<null, IntentError>(__TAURI_INVOKE("clear_configs")),
	/**  Forget which protocol last worked, so the next connect probes from the top of the order again. */
	forgetPreferredProtocol: () => typedError<null, IntentError>(__TAURI_INVOKE("forget_preferred_protocol")),
	/**  Get list of installed apps for split tunneling (Android only) */
	getInstalledApps: () => typedError<AppInfo[], string>(__TAURI_INVOKE("get_installed_apps")),
	/**  Check if battery optimization is disabled (Android only) */
	isBatteryOptimizationDisabled: () => typedError<boolean, string>(__TAURI_INVOKE("is_battery_optimization_disabled")),
	/**
	 *  Request the user to disable battery optimization (Android only)
	 *  Returns whether battery optimization is now disabled after the user responds.
	 */
	requestDisableBatteryOptimization: () => typedError<boolean, string>(__TAURI_INVOKE("request_disable_battery_optimization")),
	/**  Check if notifications are enabled (Android only) */
	areNotificationsEnabled: () => typedError<boolean, string>(__TAURI_INVOKE("are_notifications_enabled")),
	/**
	 *  Request notification permission (Android only)
	 *  Returns whether notifications are now enabled after the user responds.
	 */
	openNotificationSettings: () => typedError<boolean, string>(__TAURI_INVOKE("open_notification_settings")),
	/**  Get safe area insets (status bar, nav bar heights) in dp */
	getSafeAreaInsets: () => typedError<SafeAreaInsets, string>(__TAURI_INVOKE("get_safe_area_insets")),
	/**  Set status bar icon style to match app theme (Android only) */
	setStatusBarStyle: (isDark: boolean) => typedError<null, string>(__TAURI_INVOKE("set_status_bar_style", { isDark })),
	/**  Get current diagnostic capture status. */
	getLogCaptureStatus: () => __TAURI_INVOKE<LogCaptureStatus>("get_log_capture_status"),
	/**
	 *  Start a diagnostic capture. This enables verbose runtime logs and starts
	 *  writing capture files without changing the user's saved profile permanently.
	 */
	startLogCapture: () => typedError<LogCaptureStatus, string>(__TAURI_INVOKE("start_log_capture")),
	/**  Stop the active diagnostic capture and restore the previous runtime profile. */
	stopLogCapture: () => typedError<LogCaptureStatus, string>(__TAURI_INVOKE("stop_log_capture")),
	/**
	 *  Export latest diagnostic capture as a tar.gz archive via native save dialog.
	 *  Returns `true` if saved successfully, `false` if the user cancelled.
	 */
	exportLogs: () => typedError<boolean, string>(__TAURI_INVOKE("export_logs")),
	/**  Get the current log configuration. */
	getLogConfig: () => __TAURI_INVOKE<LogConfig>("get_log_config"),
	/**  Apply a new log configuration. Persists to disk and propagates to VPN process. */
	setLogConfig: (config: LogConfig) => typedError<null, string>(__TAURI_INVOKE("set_log_config", { config })),
	/**
	 *  Record a line the frontend wrote, under the frontend's own target.
	 * 
	 *  The webview used to reach the log through `tauri-plugin-log`, which hands the line to the
	 *  `log` crate — and every `log` record arrives in tracing as the *same* callsite, target `log`,
	 *  with the real source demoted to a `log.target` field. Third-party crates come in that way too,
	 *  so the one directive that could quiet a noisy dependency also silenced the frontend: `log=warn`
	 *  in the normal profile, and `console.info` — the level everything in the frontend is told to
	 *  use — never reached logcat at all.
	 * 
	 *  Five callsites rather than one dynamic target, because a tracing target is fixed at its
	 *  callsite: that is exactly what makes `webview=…` a filter directive of its own.
	 */
	webviewLog: (level: WebviewLevel, message: string) => __TAURI_INVOKE<void>("webview_log", { level, message }),
	/**
	 *  Hand the server session over to Rust, or take it away.
	 * 
	 *  Called by the frontend whenever any part of it changes: the token on sign-in, on every sliding
	 *  refresh and on sign-out, and the device identity as soon as the plugin reports it. `token` is
	 *  `None` exactly when the user is signed out, and then the stored session is removed rather than
	 *  left to rot — it is what a background repair would authenticate with, and a signed-out device
	 *  must not be able to make peers.
	 * 
	 *  A session that arrives incomplete (the token is there but the device id has not been read yet)
	 *  is written anyway and replaced when the rest lands: [`session::load`] refuses to return
	 *  anything it could not provision with, so a half-written one is simply not used.
	 */
	setServerSession: (baseUrl: string, token: string | null, deviceId: string | null, deviceName: string | null) => typedError<null, string>(__TAURI_INVOKE("set_server_session", { baseUrl, token, deviceId, deviceName })),
};

/** Events */
export const events = {
	tunnelStateChanged: makeEvent<TunnelStateChanged>("tunnel-state-changed"),
};

/* Types */
/**  Information about an installed app (for split tunneling UI) */
export type AppInfo = {
	package_name: string,
	label: string,
	is_system: boolean,
	icon: string | null,
};

/**
 *  Why a single attempt failed.
 * 
 *  Note what is deliberately absent: a blanket `From<String>`. The old `ConnectError` had one, and
 *  it stamped every `?`-propagated error as a generic tunnel error — which is how a DNS-resolve
 *  failure and an address-parse failure ended up indistinguishable from a dead peer. Every variant
 *  here is constructed at exactly one call site.
 */
export type AttemptError = { kind: "permission_denied" } | 
/**
 *  The consent dialog was asked for and never answered: Android refuses to start an activity
 *  for a process that is in the background, and the activity can also be recreated while the
 *  dialog is up, which loses the reply. Neither is a refusal, and neither is fixed by trying
 *  the next protocol — so, like a refusal, it ends the cycle.
 */
{ kind: "consent_unavailable" } | { kind: "no_config"; protocol: Protocol } | { kind: "platform_unavailable"; detail: string } | { kind: "resolve_failed"; host: string; detail: string } | { kind: "invalid_config"; detail: string } | { kind: "platform"; step: StepKind; detail: string } | { kind: "backend"; error: BackendError } | { kind: "verify_failed" } | { kind: "timed_out" } | { kind: "peer_start_failed"; detail: string } | { kind: "cancelled" } | 
/**
 *  The attempt task panicked or was aborted. Synthesised by the actor from the task's join
 *  error, so a crash can never leave the status waiting for a report that will not come. The
 *  ladder did *not* unwind itself: whatever it applied is recovered from the journal.
 */
{ kind: "crashed"; detail: string };

export type AttemptFailure = {
	protocol: Protocol,
	error: AttemptError,
	pass: number,
};

/**
 *  Which protocol is being probed, and how far through the order we are.
 * 
 *  Part of the *same* snapshot as [`Phase`], so the cancel/connect swap and the label can no
 *  longer disagree with each other.
 */
export type AttemptProgress = {
	protocol: Protocol,
	index: number,
	total: number,
};

/**
 *  Why the backend could not do what it was asked.
 * 
 *  Plain data, so it can travel inside an attempt's failure to the UI. The variants that matter
 *  to a caller's *decision* — as opposed to its log line — are the ones a policy hangs off:
 *  [`Self::PermissionDenied`] is what makes the desktop ladder retry once without the socket
 *  mark, and it is derived from the OS error kind, never from the wording of a message that a
 *  `setlocale` may have translated.
 */
export type BackendError = 
/**
 *  The OS refused a privileged operation. On Linux that is `SO_MARK`, which needs
 *  `CAP_NET_ADMIN`.
 */
{ kind: "permission_denied"; detail: string } | 
/**  The config cannot be turned into a tunnel: a malformed key, address or AWG parameter. */
{ kind: "invalid_config"; detail: string } | 
/**  The tunnel engine or its device failed to start or stop. */
{ kind: "engine"; detail: string } | 
/**  Nothing is running to be pinged. */
{ kind: "not_running" } | 
/**
 *  Cross-process only: the service could not be reached, or the call to it failed in
 *  transit. Says nothing about whether a tunnel exists.
 */
{ kind: "service_unreachable"; detail: string } | 
/**  Cross-process only: the service answered, and the answer was a refusal. */
{ kind: "service_refused"; detail: string } | 
/**
 *  The operation does not exist on this backend: an in-process backend has no service to
 *  ask, and a cross-process one starts nothing itself.
 */
{ kind: "unsupported" };

export type ConfigError = { kind: "empty" } | { kind: "unparseable"; detail: string } | 
/**  A transport failure, not a config problem: nothing looked at the config at all. */
{ kind: "actor_gone" };

export type ConfigSummary = {
	protocol: Protocol,
	address: string,
	server_endpoint: string,
	dns: string | null,
	allowed_ips: string,
	mtu: number,
};

/**
 *  `available` is a set; the order lives only in an [`UpIntent`]. `preferred` is "the protocol that
 *  last actually worked", written only after a successful attempt — never before a probe.
 */
export type ConfigsView = {
	available: Protocol[],
	preferred: Protocol | null,
	summaries: ConfigSummary[],
};

/**  How a cycle ended. */
export type CycleOutcome = { outcome: "connected"; protocol: Protocol; adopted: boolean; 
/**
 *  What failed on the way here, if the ladder had to step over anything.
 * 
 *  A cycle that ends connected is not a cycle in which nothing went wrong: the ladder
 *  tries protocols in order, so AmneziaWG can fail to verify — the signal that its peer
 *  was deleted server-side — and WireGuard carry the connection a second later. Reporting
 *  only the winner left that dead peer in place until something else happened to notice
 *  it, which on device meant the next app start.
 */
failures: AttemptFailure[] } | 
/**
 *  Every protocol in the order failed, for every allowed pass — or one failed fatally.
 * 
 *  `failures` carries one entry per probe, so the caller can find exactly which protocol
 *  reported `verify_failed` and re-provision *that* peer, instead of assuming it was whichever
 *  protocol happened to be tried last.
 */
{ outcome: "exhausted"; failures: AttemptFailure[] } | 
/**  Was connected, the tunnel died, the reconnect budget ran out. */
{ outcome: "lost_gave_up"; protocol: Protocol; passes: number } | 
/**
 *  A teardown could not be confirmed: after the allowed re-runs the world still reported a
 *  running tunnel. The intent is demoted and the machine may be dirty.
 */
{ outcome: "unwind_failed" } | 
/**  Superseded by a newer intent, or torn down by an explicit Down. */
{ outcome: "cancelled" } | 
/**  An explicit Down reached terminal Down. */
{ outcome: "down" };

export type IntentAccepted = {
	epoch: IntentEpoch,
};

/**
 *  Monotonic, bumped on every accepted intent change — including Down.
 * 
 *  Carried into the Android service and echoed back by it, so an observation from a previous
 *  service instance, or a stop for a superseded generation, is rejectable by value rather than by
 *  guesswork.
 */
export type IntentEpoch = number;

export type IntentError = { kind: "empty_order" } | { kind: "no_usable_config" } | { kind: "actor_gone" } | { kind: "settle_timeout" };

export type IntentView = "down" | "up";

export type LogCaptureStatus = {
	active: boolean,
	capture_id: string | null,
};

/**  Persistent runtime logging configuration. */
export type LogConfig = {
	/**  Active profile for runtime logs (logcat/stdout and capture files). */
	profile?: LogProfile,
	/**  Optional raw RUST_LOG-style filter string, stored separately from activation. */
	custom_filter?: string | null,
	/**  When true, `custom_filter` replaces the selected profile. */
	custom_filter_enabled?: boolean,
};

export type LogProfile = "normal" | "verbose";

/**
 *  The five original status literals are preserved verbatim so the existing indicator component
 *  and its translation keys keep working. `Retrying` and `Unknown` are the additions.
 */
export type Phase = 
/**
 *  We have not yet had an authoritative look at the world.
 * 
 *  Distinct from [`Self::Disconnected`], which is a claim: there is no tunnel. Collapsing the
 *  two is why opening the app with a tunnel already running flashed "disconnected" before the
 *  first observation landed — the UI reported an answer it did not have yet.
 */
"unknown" | "disconnected" | "connecting" | "verifying_connection" | "connected" | "disconnecting" | "retrying";

/**
 *  The ONLY protocol representation in the crate.
 * 
 *  The serde renames are load-bearing: these exact strings are already on users' disks and in
 *  their OS keyrings via the old `SavedVpnConfigs.active_protocol: String`, and in all three
 *  arms of the migration chain in `config.rs::parse_stored_configs`.
 */
export type Protocol = "wireguard" | "amneziawg" | "vless";

export type RetryProgress = {
	pass: number,
	max: number,
	resume_in_ms: number,
};

/**  Safe area insets (status bar, nav bar) in dp */
export type SafeAreaInsets = {
	top: number | null,
	bottom: number | null,
};

export type SplitMode = "all" | "include" | "exclude";

export type StepKind = "prepare_link" | "start_backend" | "address" | "endpoint_route" | "routes" | "dns" | "android_service";

export type TrafficStats = {
	tx_bytes: number,
	rx_bytes: number,
	tx_bytes_per_sec: number | null,
	rx_bytes_per_sec: number | null,
};

/**
 *  Everything a *self-initiated* reconnect needs, because at reconnect time there is no caller to
 *  supply it. `apps` is sorted and deduped on construction, so `PartialEq` means "the same tunnel"
 *  rather than "the same list written the same way".
 */
export type TunnelParams = {
	split_mode: SplitMode,
	apps: string[],
};

/**  Everything the UI can know about the tunnel, in one value. */
export type TunnelState = {
	/**
	 *  Bumped only when a state is actually published. Consumers drop any snapshot whose `seq` is
	 *  not newer than the one they hold, which closes the seed-versus-first-event race at startup.
	 */
	seq: number,
	phase: Phase,
	/**
	 *  [`Phase::is_busy`] for [`Self::phase`], carried so the consumer never restates which phases
	 *  count as work in progress.
	 */
	busy: boolean,
	/**  [`Phase::is_cancellable`] for [`Self::phase`]. */
	cancellable: boolean,
	intent: IntentView,
	epoch: IntentEpoch,
	intent_order: Protocol[],
	/**  The protocol actually running — distinct from the preferred one. */
	protocol: Protocol | null,
	/**
	 *  The split rules the running tunnel was actually built with, when they are known.
	 * 
	 *  `None` when nothing is running, and for an adopted tunnel whose owner does not report them
	 *  (only the in-process backend, which cannot find a tunnel it did not start). Published
	 *  because it is the only way the UI can tell "the settings changed since this tunnel came
	 *  up" from data: that used to be a component flag, which a moment of `retrying` cleared and
	 *  leaving the page destroyed — while the tunnel carried on with the old rules.
	 */
	params: TunnelParams | null,
	adopted: boolean,
	attempt: AttemptProgress | null,
	retry: RetryProgress | null,
	server_endpoint: string | null,
	assigned_ip: string | null,
	connected_at: number | null,
	last_packet_received: number | null,
	stats: TrafficStats,
	/**  Sticky until the next accepted intent. */
	last_outcome: CycleOutcome | null,
	/**
	 *  Which cycle [`Self::last_outcome`] came from, counting up from zero.
	 * 
	 *  The only thing that identifies an outcome. Neither the intent's epoch nor the outcome's own
	 *  tag can do it: a reconnect runs under the *same* intent, so a tunnel that dropped and came
	 *  back reports `connected` twice under one epoch — and a consumer deduplicating by that pair
	 *  swallowed the second, which is precisely the one that says a protocol was stepped over.
	 */
	outcome_serial: number,
	configs: ConfigsView,
	/**  False while the world is dark. This never by itself means the tunnel is down. */
	backend_reachable: boolean,
};

/**
 *  Emitted whenever the actor publishes a new state.
 * 
 *  The payload carries a `seq` that only ever increases, so a listener can drop anything not
 *  strictly newer than what it already holds — which is what closes the race between seeding from
 *  a direct read at startup and receiving the first pushed update.
 */
export type TunnelStateChanged = TunnelState;

/**  Where a line the webview wrote sits against the rest of the log. */
export type WebviewLevel = "trace" | "debug" | "info" | "warn" | "error";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

