[package]
name = "floppa-cli"
version = "0.1.0"
edition = "2024"
license.workspace = true
description = "CLI client for Floppa VPN"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive", "env"] }
serde_json = "1"
anyhow = "1"
dirs = "6"
open = "5"
tracing-subscriber.workspace = true
tracing-appender = "0.2.4"
uuid = { version = "1.25.0", features = ["v4"] }
url = "2.5.8"
base64.workspace = true
floppa-api-client = { version = "0.1.0", path = "../floppa-api-client" }
floppa-vpn-core = { version = "0.1.0", path = "../floppa-vpn-core" }
# Uncomment for local development, comment out before commit/push:
# shoes-lite = { path = "../../rust/shoes-lite" }
