/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangelogModal: typeof import('./src/components/ChangelogModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UFieldGroup: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UIcon: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelect: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTable: typeof import('./../node_modules/.bun/@nuxt+ui@4.5.0+09a2a9c570477cd9/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    VpnCard: typeof import('./src/components/VpnCard.vue')['default']
  }
}
