// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMyPeerData, CreateMyPeerErrors, CreateMyPeerResponses, CreatePlanData, CreatePlanErrors, CreatePlanResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteAdminPeerData, DeleteAdminPeerErrors, DeleteAdminPeerResponses, DeleteMyPeerData, DeleteMyPeerErrors, DeleteMyPeerResponses, DeletePlanData, DeletePlanErrors, DeletePlanResponses, DeleteSubscriptionData, DeleteSubscriptionErrors, DeleteSubscriptionResponses, ExchangeTelegramLoginCodeData, ExchangeTelegramLoginCodeErrors, ExchangeTelegramLoginCodeResponses, GetMeData, GetMeErrors, GetMeResponses, GetMyPeerByDeviceData, GetMyPeerByDeviceErrors, GetMyPeerByDeviceResponses, GetMyPeerConfigData, GetMyPeerConfigErrors, GetMyPeerConfigResponses, GetMyPeersData, GetMyPeersErrors, GetMyPeersResponses, GetMyVlessConfigData, GetMyVlessConfigErrors, GetMyVlessConfigResponses, GetPublicConfigData, GetPublicConfigResponses, GetStatsData, GetStatsErrors, GetStatsResponses, GetUserData, GetUserErrors, GetUserResponses, GetVersionData, GetVersionResponses, ListPeersData, ListPeersErrors, ListPeersResponses, ListPlansData, ListPlansErrors, ListPlansResponses, ListUsersData, ListUsersErrors, ListUsersResponses, RegenerateMyVlessConfigData, RegenerateMyVlessConfigErrors, RegenerateMyVlessConfigResponses, RemovePeerData, RemovePeerErrors, RemovePeerResponses, SendMyPeerConfigData, SendMyPeerConfigErrors, SendMyPeerConfigResponses, SetSubscriptionData, SetSubscriptionErrors, SetSubscriptionResponses, StartTelegramDeepLinkLoginData, StartTelegramDeepLinkLoginErrors, StartTelegramDeepLinkLoginResponses, TelegramDeepLinkCallbackData, TelegramDeepLinkCallbackErrors, TelegramLoginData, TelegramLoginErrors, TelegramLoginResponses, TelegramMiniAppAuthData, TelegramMiniAppAuthErrors, TelegramMiniAppAuthResponses, UpdatePlanData, UpdatePlanErrors, UpdatePlanResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Authenticate via Telegram Login Widget
 */
export const telegramLogin = <ThrowOnError extends boolean = false>(options: Options<TelegramLoginData, ThrowOnError>) => (options.client ?? client).post<TelegramLoginResponses, TelegramLoginErrors, ThrowOnError>({
    url: '/auth/telegram',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Telegram widget callback for deep-link flow.
 */
export const telegramDeepLinkCallback = <ThrowOnError extends boolean = false>(options?: Options<TelegramDeepLinkCallbackData, ThrowOnError>) => (options?.client ?? client).get<unknown, TelegramDeepLinkCallbackErrors, ThrowOnError>({ url: '/auth/telegram/callback', ...options });

/**
 * Exchange one-time login code for JWT + user payload.
 */
export const exchangeTelegramLoginCode = <ThrowOnError extends boolean = false>(options: Options<ExchangeTelegramLoginCodeData, ThrowOnError>) => (options.client ?? client).post<ExchangeTelegramLoginCodeResponses, ExchangeTelegramLoginCodeErrors, ThrowOnError>({
    url: '/auth/telegram/exchange-code',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Authenticate via Telegram Mini App initData
 */
export const telegramMiniAppAuth = <ThrowOnError extends boolean = false>(options: Options<TelegramMiniAppAuthData, ThrowOnError>) => (options.client ?? client).post<TelegramMiniAppAuthResponses, TelegramMiniAppAuthErrors, ThrowOnError>({
    url: '/auth/telegram/mini-app',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Render the Telegram login page for deep-link flow.
 */
export const startTelegramDeepLinkLogin = <ThrowOnError extends boolean = false>(options: Options<StartTelegramDeepLinkLoginData, ThrowOnError>) => (options.client ?? client).get<StartTelegramDeepLinkLoginResponses, StartTelegramDeepLinkLoginErrors, ThrowOnError>({ url: '/auth/telegram/start', ...options });

/**
 * Get public configuration
 */
export const getPublicConfig = <ThrowOnError extends boolean = false>(options?: Options<GetPublicConfigData, ThrowOnError>) => (options?.client ?? client).get<GetPublicConfigResponses, unknown, ThrowOnError>({ url: '/config', ...options });

/**
 * Get current authenticated user info
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({ url: '/me', ...options });

/**
 * List current user's peers
 */
export const getMyPeers = <ThrowOnError extends boolean = false>(options?: Options<GetMyPeersData, ThrowOnError>) => (options?.client ?? client).get<GetMyPeersResponses, GetMyPeersErrors, ThrowOnError>({ url: '/me/peers', ...options });

/**
 * Create a new WireGuard peer for the current user
 */
export const createMyPeer = <ThrowOnError extends boolean = false>(options?: Options<CreateMyPeerData, ThrowOnError>) => (options?.client ?? client).post<CreateMyPeerResponses, CreateMyPeerErrors, ThrowOnError>({
    url: '/me/peers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get a peer by device_id for the current user
 */
export const getMyPeerByDevice = <ThrowOnError extends boolean = false>(options: Options<GetMyPeerByDeviceData, ThrowOnError>) => (options.client ?? client).get<GetMyPeerByDeviceResponses, GetMyPeerByDeviceErrors, ThrowOnError>({ url: '/me/peers/by-device/{device_id}', ...options });

/**
 * Delete a peer owned by the current user
 */
export const deleteMyPeer = <ThrowOnError extends boolean = false>(options: Options<DeleteMyPeerData, ThrowOnError>) => (options.client ?? client).delete<DeleteMyPeerResponses, DeleteMyPeerErrors, ThrowOnError>({ url: '/me/peers/{id}', ...options });

/**
 * Get WireGuard config for a peer owned by the current user
 */
export const getMyPeerConfig = <ThrowOnError extends boolean = false>(options: Options<GetMyPeerConfigData, ThrowOnError>) => (options.client ?? client).get<GetMyPeerConfigResponses, GetMyPeerConfigErrors, ThrowOnError>({ url: '/me/peers/{id}/config', ...options });

/**
 * Send WireGuard config to user via Telegram bot
 */
export const sendMyPeerConfig = <ThrowOnError extends boolean = false>(options: Options<SendMyPeerConfigData, ThrowOnError>) => (options.client ?? client).post<SendMyPeerConfigResponses, SendMyPeerConfigErrors, ThrowOnError>({ url: '/me/peers/{id}/send-config', ...options });

/**
 * Get VLESS config for the current user (generates UUID on first call)
 */
export const getMyVlessConfig = <ThrowOnError extends boolean = false>(options?: Options<GetMyVlessConfigData, ThrowOnError>) => (options?.client ?? client).get<GetMyVlessConfigResponses, GetMyVlessConfigErrors, ThrowOnError>({ url: '/me/vless-config', ...options });

/**
 * Regenerate VLESS UUID for the current user (old UUID stops working immediately)
 */
export const regenerateMyVlessConfig = <ThrowOnError extends boolean = false>(options?: Options<RegenerateMyVlessConfigData, ThrowOnError>) => (options?.client ?? client).post<RegenerateMyVlessConfigResponses, RegenerateMyVlessConfigErrors, ThrowOnError>({ url: '/me/vless-config/regenerate', ...options });

/**
 * List all peers (admin only)
 */
export const listPeers = <ThrowOnError extends boolean = false>(options?: Options<ListPeersData, ThrowOnError>) => (options?.client ?? client).get<ListPeersResponses, ListPeersErrors, ThrowOnError>({ url: '/peers', ...options });

/**
 * Delete a peer by ID (admin only)
 */
export const deleteAdminPeer = <ThrowOnError extends boolean = false>(options: Options<DeleteAdminPeerData, ThrowOnError>) => (options.client ?? client).delete<DeleteAdminPeerResponses, DeleteAdminPeerErrors, ThrowOnError>({ url: '/peers/{id}', ...options });

/**
 * List all plans (admin only)
 */
export const listPlans = <ThrowOnError extends boolean = false>(options?: Options<ListPlansData, ThrowOnError>) => (options?.client ?? client).get<ListPlansResponses, ListPlansErrors, ThrowOnError>({ url: '/plans', ...options });

/**
 * Create a new plan (admin only)
 */
export const createPlan = <ThrowOnError extends boolean = false>(options: Options<CreatePlanData, ThrowOnError>) => (options.client ?? client).post<CreatePlanResponses, CreatePlanErrors, ThrowOnError>({
    url: '/plans',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a plan (admin only). Fails if plan has subscriptions.
 */
export const deletePlan = <ThrowOnError extends boolean = false>(options: Options<DeletePlanData, ThrowOnError>) => (options.client ?? client).delete<DeletePlanResponses, DeletePlanErrors, ThrowOnError>({ url: '/plans/{id}', ...options });

/**
 * Update a plan (admin only)
 */
export const updatePlan = <ThrowOnError extends boolean = false>(options: Options<UpdatePlanData, ThrowOnError>) => (options.client ?? client).patch<UpdatePlanResponses, UpdatePlanErrors, ThrowOnError>({
    url: '/plans/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get system statistics (admin only)
 */
export const getStats = <ThrowOnError extends boolean = false>(options?: Options<GetStatsData, ThrowOnError>) => (options?.client ?? client).get<GetStatsResponses, GetStatsErrors, ThrowOnError>({ url: '/stats', ...options });

/**
 * List all users (admin only)
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({ url: '/users', ...options });

/**
 * Pre-register a user by telegram_id and assign a subscription (admin only).
 * When the user later authenticates via Telegram, their account and subscription will be waiting.
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    url: '/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get user details (admin only)
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({ url: '/users/{id}', ...options });

/**
 * Remove all active peers for a user (admin only)
 */
export const removePeer = <ThrowOnError extends boolean = false>(options: Options<RemovePeerData, ThrowOnError>) => (options.client ?? client).delete<RemovePeerResponses, RemovePeerErrors, ThrowOnError>({ url: '/users/{id}/peer', ...options });

/**
 * Delete (expire) a user's active subscription (admin only)
 */
export const deleteSubscription = <ThrowOnError extends boolean = false>(options: Options<DeleteSubscriptionData, ThrowOnError>) => (options.client ?? client).delete<DeleteSubscriptionResponses, DeleteSubscriptionErrors, ThrowOnError>({ url: '/users/{id}/subscription', ...options });

/**
 * Set (create or replace) a user's subscription (admin only).
 * If the user already has an active subscription, it will be expired first.
 */
export const setSubscription = <ThrowOnError extends boolean = false>(options: Options<SetSubscriptionData, ThrowOnError>) => (options.client ?? client).put<SetSubscriptionResponses, SetSubscriptionErrors, ThrowOnError>({
    url: '/users/{id}/subscription',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getVersion = <ThrowOnError extends boolean = false>(options?: Options<GetVersionData, ThrowOnError>) => (options?.client ?? client).get<GetVersionResponses, unknown, ThrowOnError>({ url: '/version', ...options });
