// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiError = {
    error: string;
    message: string;
};

export type AuthResponse = {
    token: string;
    user: AuthUserInfo;
};

export type AuthUserInfo = {
    first_name?: string | null;
    id: number;
    is_admin: boolean;
    last_name?: string | null;
    photo_url?: string | null;
    username?: string | null;
};

export type CreatePeerRequest = {
    device_id?: string | null;
    device_name?: string | null;
    installation_id?: number | null;
};

export type CreatePeerResponse = {
    assigned_ip: string;
    config: string;
    id: number;
};

export type CreatePlanRequest = {
    default_speed_limit_mbps?: number | null;
    display_name: string;
    is_public?: boolean;
    max_peers?: number;
    name: string;
    period_days?: number | null;
    price_rub?: number;
    price_stars?: number | null;
    trial_days?: number | null;
};

export type CreateUserRequest = {
    /**
     * Duration in days. Required unless `permanent` is true.
     */
    days?: number | null;
    /**
     * Display name for the user (shown until they register and Telegram provides real name).
     */
    first_name?: string | null;
    /**
     * If true, creates a permanent subscription (no expiration date).
     */
    permanent?: boolean;
    plan_id: number;
    telegram_id: number;
    username?: string | null;
};

export type CreateUserResponse = {
    id: number;
};

export type ExchangeTelegramLoginCodeRequest = {
    code: string;
};

export type InstallationResponse = {
    app_version?: string | null;
    created_at: string;
    device_id: string;
    device_name?: string | null;
    id: number;
    last_seen_at: string;
    platform?: string | null;
};

export type InstallationSummary = {
    app_version?: string | null;
    created_at: string;
    device_id: string;
    device_name?: string | null;
    has_vless: boolean;
    has_wg: boolean;
    id: number;
    last_seen_at: string;
    platform?: string | null;
    user_id: number;
    username?: string | null;
};

export type MeResponse = {
    first_name?: string | null;
    id: number;
    is_admin: boolean;
    last_name?: string | null;
    photo_url?: string | null;
    subscription?: null | MySubscription;
    telegram_id: number;
    username?: string | null;
};

export type MiniAppAuthRequest = {
    init_data: string;
};

export type MyPeer = {
    assigned_ip: string;
    created_at: string;
    device_id?: string | null;
    device_name?: string | null;
    download_bytes: number;
    id: number;
    last_handshake?: string | null;
    sync_status: string;
    upload_bytes: number;
};

export type MyPeersResponse = {
    peers: Array<MyPeer>;
    vless?: null | VlessInfo;
};

export type MySubscription = {
    expires_at?: string | null;
    max_peers: number;
    plan_display_name: string;
    plan_name: string;
    speed_limit_mbps?: number | null;
    starts_at: string;
};

export type PeerDetail = {
    assigned_ip: string;
    device_id?: string | null;
    device_name?: string | null;
    download_bytes: number;
    id: number;
    last_handshake?: string | null;
    public_key: string;
    sync_status: string;
    upload_bytes: number;
};

export type PeerSummary = {
    assigned_ip: string;
    client_version?: string | null;
    device_id?: string | null;
    device_name?: string | null;
    download_bytes: number;
    has_vless: boolean;
    id: number;
    last_handshake?: string | null;
    plan_name?: string | null;
    sync_status: string;
    upload_bytes: number;
    user_id: number;
    username?: string | null;
};

export type Plan = {
    default_speed_limit_mbps?: number | null;
    display_name: string;
    id: number;
    is_public: boolean;
    max_peers: number;
    name: string;
    period_days?: number | null;
    price_rub: number;
    price_stars?: number | null;
    trial_days?: number | null;
};

export type PublicConfig = {
    telegram_bot_username?: string | null;
};

export type SetSubscriptionRequest = {
    /**
     * Duration in days. If omitted, uses the plan's trial_days (for trial plans).
     * Use `permanent: true` to create a subscription with no expiration.
     */
    days?: number | null;
    /**
     * If true, creates a permanent subscription (no expiration date).
     */
    permanent?: boolean;
    plan_id: number;
};

export type Stats = {
    active_peers: number;
    active_subscriptions: number;
    total_download_bytes: number;
    total_payments: number;
    total_stars_revenue: number;
    total_upload_bytes: number;
    total_users: number;
};

export type SubscriptionDetail = {
    expires_at?: string | null;
    id: number;
    is_active: boolean;
    max_peers: number;
    plan_display_name: string;
    plan_id: number;
    plan_name: string;
    source: string;
    speed_limit_mbps?: number | null;
    starts_at: string;
};

/**
 * Data received from Telegram Login Widget
 */
export type TelegramAuthData = {
    auth_date: number;
    first_name?: string | null;
    hash: string;
    id: number;
    last_name?: string | null;
    photo_url?: string | null;
    username?: string | null;
};

export type UpdatePlanRequest = {
    clear_period_days?: boolean;
    clear_price_stars?: boolean;
    clear_speed_limit?: boolean;
    clear_trial_days?: boolean;
    default_speed_limit_mbps?: number | null;
    display_name?: string | null;
    is_public?: boolean | null;
    max_peers?: number | null;
    period_days?: number | null;
    price_rub?: number | null;
    price_stars?: number | null;
    trial_days?: number | null;
};

export type UpsertInstallationRequest = {
    app_version?: string | null;
    device_id: string;
    device_name?: string | null;
    platform?: string | null;
};

export type UserDetail = {
    created_at: string;
    first_name?: string | null;
    id: number;
    is_admin: boolean;
    last_name?: string | null;
    peers: Array<PeerDetail>;
    photo_url?: string | null;
    subscriptions: Array<SubscriptionDetail>;
    telegram_id: number;
    username?: string | null;
    vless?: null | VlessAdminInfo;
};

export type UserSummary = {
    active_plan?: string | null;
    client_version?: string | null;
    created_at: string;
    first_name?: string | null;
    has_vless: boolean;
    id: number;
    is_admin: boolean;
    last_name?: string | null;
    peer_count: number;
    photo_url?: string | null;
    telegram_id: number;
    username?: string | null;
};

export type VersionInfo = {
    build_time: string;
    git_hash: string;
    version: string;
};

export type VlessAdminInfo = {
    download_bytes: number;
    has_uuid: boolean;
    upload_bytes: number;
};

export type VlessConfigResponse = {
    uri: string;
};

export type VlessInfo = {
    download_bytes: number;
    /**
     * Whether the user has generated a VLESS UUID
     */
    has_uuid: boolean;
    upload_bytes: number;
};

export type VlessPeerSummary = {
    app_version?: string | null;
    device_name?: string | null;
    download_bytes: number;
    has_wg: boolean;
    plan_name?: string | null;
    upload_bytes: number;
    user_id: number;
    username?: string | null;
};

export type TelegramLoginData = {
    body: TelegramAuthData;
    path?: never;
    query?: never;
    url: '/auth/telegram';
};

export type TelegramLoginErrors = {
    /**
     * Invalid Telegram auth data
     */
    401: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type TelegramLoginError = TelegramLoginErrors[keyof TelegramLoginErrors];

export type TelegramLoginResponses = {
    200: AuthResponse;
};

export type TelegramLoginResponse = TelegramLoginResponses[keyof TelegramLoginResponses];

export type TelegramDeepLinkCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/telegram/callback';
};

export type TelegramDeepLinkCallbackErrors = {
    /**
     * Invalid or expired state
     */
    400: ApiError;
    /**
     * Invalid Telegram auth payload
     */
    401: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type TelegramDeepLinkCallbackError = TelegramDeepLinkCallbackErrors[keyof TelegramDeepLinkCallbackErrors];

export type ExchangeTelegramLoginCodeData = {
    body: ExchangeTelegramLoginCodeRequest;
    path?: never;
    query?: never;
    url: '/auth/telegram/exchange-code';
};

export type ExchangeTelegramLoginCodeErrors = {
    /**
     * Invalid or expired code
     */
    401: ApiError;
};

export type ExchangeTelegramLoginCodeError = ExchangeTelegramLoginCodeErrors[keyof ExchangeTelegramLoginCodeErrors];

export type ExchangeTelegramLoginCodeResponses = {
    200: AuthResponse;
};

export type ExchangeTelegramLoginCodeResponse = ExchangeTelegramLoginCodeResponses[keyof ExchangeTelegramLoginCodeResponses];

export type TelegramMiniAppAuthData = {
    body: MiniAppAuthRequest;
    path?: never;
    query?: never;
    url: '/auth/telegram/mini-app';
};

export type TelegramMiniAppAuthErrors = {
    /**
     * Invalid Mini App initData
     */
    401: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type TelegramMiniAppAuthError = TelegramMiniAppAuthErrors[keyof TelegramMiniAppAuthErrors];

export type TelegramMiniAppAuthResponses = {
    200: AuthResponse;
};

export type TelegramMiniAppAuthResponse = TelegramMiniAppAuthResponses[keyof TelegramMiniAppAuthResponses];

export type StartTelegramDeepLinkLoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Deep link URI, e.g. floppa://auth
         */
        redirect_uri: string;
    };
    url: '/auth/telegram/start';
};

export type StartTelegramDeepLinkLoginErrors = {
    /**
     * Invalid request
     */
    400: ApiError;
    /**
     * Server misconfiguration
     */
    500: ApiError;
};

export type StartTelegramDeepLinkLoginError = StartTelegramDeepLinkLoginErrors[keyof StartTelegramDeepLinkLoginErrors];

export type StartTelegramDeepLinkLoginResponses = {
    /**
     * HTML login page
     */
    200: unknown;
};

export type GetPublicConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/config';
};

export type GetPublicConfigResponses = {
    200: PublicConfig;
};

export type GetPublicConfigResponse = GetPublicConfigResponses[keyof GetPublicConfigResponses];

export type ListInstallationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/installations';
};

export type ListInstallationsErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type ListInstallationsError = ListInstallationsErrors[keyof ListInstallationsErrors];

export type ListInstallationsResponses = {
    200: Array<InstallationSummary>;
};

export type ListInstallationsResponse = ListInstallationsResponses[keyof ListInstallationsResponses];

export type DeleteInstallationData = {
    body?: never;
    path: {
        /**
         * Installation ID
         */
        id: number;
    };
    query?: never;
    url: '/installations/{id}';
};

export type DeleteInstallationErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Installation not found
     */
    404: ApiError;
};

export type DeleteInstallationError = DeleteInstallationErrors[keyof DeleteInstallationErrors];

export type DeleteInstallationResponses = {
    /**
     * Installation deleted
     */
    200: unknown;
};

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    200: MeResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpsertMyInstallationData = {
    body: UpsertInstallationRequest;
    path?: never;
    query?: never;
    url: '/me/installations';
};

export type UpsertMyInstallationErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type UpsertMyInstallationError = UpsertMyInstallationErrors[keyof UpsertMyInstallationErrors];

export type UpsertMyInstallationResponses = {
    200: InstallationResponse;
};

export type UpsertMyInstallationResponse = UpsertMyInstallationResponses[keyof UpsertMyInstallationResponses];

export type GetMyPeersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/peers';
};

export type GetMyPeersErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type GetMyPeersError = GetMyPeersErrors[keyof GetMyPeersErrors];

export type GetMyPeersResponses = {
    200: MyPeersResponse;
};

export type GetMyPeersResponse = GetMyPeersResponses[keyof GetMyPeersResponses];

export type CreateMyPeerData = {
    body?: null | CreatePeerRequest;
    path?: never;
    query?: never;
    url: '/me/peers';
};

export type CreateMyPeerErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * No active subscription
     */
    402: ApiError;
    /**
     * Peer limit reached
     */
    403: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type CreateMyPeerError = CreateMyPeerErrors[keyof CreateMyPeerErrors];

export type CreateMyPeerResponses = {
    200: CreatePeerResponse;
};

export type CreateMyPeerResponse = CreateMyPeerResponses[keyof CreateMyPeerResponses];

export type GetMyPeerByDeviceData = {
    body?: never;
    path: {
        /**
         * Device UUID
         */
        device_id: string;
    };
    query?: never;
    url: '/me/peers/by-device/{device_id}';
};

export type GetMyPeerByDeviceErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * No peer for this device
     */
    404: ApiError;
};

export type GetMyPeerByDeviceError = GetMyPeerByDeviceErrors[keyof GetMyPeerByDeviceErrors];

export type GetMyPeerByDeviceResponses = {
    200: MyPeer;
};

export type GetMyPeerByDeviceResponse = GetMyPeerByDeviceResponses[keyof GetMyPeerByDeviceResponses];

export type DeleteMyPeerData = {
    body?: never;
    path: {
        /**
         * Peer ID
         */
        id: number;
    };
    query?: never;
    url: '/me/peers/{id}';
};

export type DeleteMyPeerErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Peer not found
     */
    404: ApiError;
};

export type DeleteMyPeerError = DeleteMyPeerErrors[keyof DeleteMyPeerErrors];

export type DeleteMyPeerResponses = {
    /**
     * Peer deleted
     */
    200: unknown;
};

export type GetMyPeerConfigData = {
    body?: never;
    path: {
        /**
         * Peer ID
         */
        id: number;
    };
    query?: never;
    url: '/me/peers/{id}/config';
};

export type GetMyPeerConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Peer not found
     */
    404: ApiError;
};

export type GetMyPeerConfigError = GetMyPeerConfigErrors[keyof GetMyPeerConfigErrors];

export type GetMyPeerConfigResponses = {
    /**
     * WireGuard .conf
     */
    200: string;
};

export type GetMyPeerConfigResponse = GetMyPeerConfigResponses[keyof GetMyPeerConfigResponses];

export type SendMyPeerConfigData = {
    body?: never;
    path: {
        /**
         * Peer ID
         */
        id: number;
    };
    query?: never;
    url: '/me/peers/{id}/send-config';
};

export type SendMyPeerConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Peer not found
     */
    404: ApiError;
    /**
     * Failed to send via Telegram
     */
    502: ApiError;
};

export type SendMyPeerConfigError = SendMyPeerConfigErrors[keyof SendMyPeerConfigErrors];

export type SendMyPeerConfigResponses = {
    /**
     * Config sent via Telegram
     */
    200: unknown;
};

export type GetMyVlessConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/vless-config';
};

export type GetMyVlessConfigErrors = {
    /**
     * VLESS not configured
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * No active subscription
     */
    402: ApiError;
};

export type GetMyVlessConfigError = GetMyVlessConfigErrors[keyof GetMyVlessConfigErrors];

export type GetMyVlessConfigResponses = {
    200: VlessConfigResponse;
};

export type GetMyVlessConfigResponse = GetMyVlessConfigResponses[keyof GetMyVlessConfigResponses];

export type RegenerateMyVlessConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/vless-config/regenerate';
};

export type RegenerateMyVlessConfigErrors = {
    /**
     * VLESS not configured
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * No active subscription
     */
    402: ApiError;
};

export type RegenerateMyVlessConfigError = RegenerateMyVlessConfigErrors[keyof RegenerateMyVlessConfigErrors];

export type RegenerateMyVlessConfigResponses = {
    200: VlessConfigResponse;
};

export type RegenerateMyVlessConfigResponse = RegenerateMyVlessConfigResponses[keyof RegenerateMyVlessConfigResponses];

export type ListPeersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/peers';
};

export type ListPeersErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type ListPeersError = ListPeersErrors[keyof ListPeersErrors];

export type ListPeersResponses = {
    200: Array<PeerSummary>;
};

export type ListPeersResponse = ListPeersResponses[keyof ListPeersResponses];

export type DeleteAdminPeerData = {
    body?: never;
    path: {
        /**
         * Peer ID
         */
        id: number;
    };
    query?: never;
    url: '/peers/{id}';
};

export type DeleteAdminPeerErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Peer not found or not active
     */
    404: ApiError;
};

export type DeleteAdminPeerError = DeleteAdminPeerErrors[keyof DeleteAdminPeerErrors];

export type DeleteAdminPeerResponses = {
    /**
     * Peer deleted
     */
    200: unknown;
};

export type ListPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/plans';
};

export type ListPlansErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type ListPlansError = ListPlansErrors[keyof ListPlansErrors];

export type ListPlansResponses = {
    200: Array<Plan>;
};

export type ListPlansResponse = ListPlansResponses[keyof ListPlansResponses];

export type CreatePlanData = {
    body: CreatePlanRequest;
    path?: never;
    query?: never;
    url: '/plans';
};

export type CreatePlanErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type CreatePlanError = CreatePlanErrors[keyof CreatePlanErrors];

export type CreatePlanResponses = {
    201: Plan;
};

export type CreatePlanResponse = CreatePlanResponses[keyof CreatePlanResponses];

export type DeletePlanData = {
    body?: never;
    path: {
        /**
         * Plan ID
         */
        id: number;
    };
    query?: never;
    url: '/plans/{id}';
};

export type DeletePlanErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Plan not found
     */
    404: ApiError;
    /**
     * Plan has existing subscriptions
     */
    409: ApiError;
};

export type DeletePlanError = DeletePlanErrors[keyof DeletePlanErrors];

export type DeletePlanResponses = {
    /**
     * Plan deleted
     */
    204: void;
};

export type DeletePlanResponse = DeletePlanResponses[keyof DeletePlanResponses];

export type UpdatePlanData = {
    body: UpdatePlanRequest;
    path: {
        /**
         * Plan ID
         */
        id: number;
    };
    query?: never;
    url: '/plans/{id}';
};

export type UpdatePlanErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Plan not found
     */
    404: ApiError;
};

export type UpdatePlanError = UpdatePlanErrors[keyof UpdatePlanErrors];

export type UpdatePlanResponses = {
    200: Plan;
};

export type UpdatePlanResponse = UpdatePlanResponses[keyof UpdatePlanResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type GetStatsError = GetStatsErrors[keyof GetStatsErrors];

export type GetStatsResponses = {
    200: Stats;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    200: Array<UserSummary>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Days not specified and plan has no trial_days
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Plan not found
     */
    404: ApiError;
    /**
     * User with this telegram_id already exists
     */
    409: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    201: CreateUserResponse;
};

export type CreateUserResponse2 = CreateUserResponses[keyof CreateUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * User not found
     */
    404: ApiError;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    200: UserDetail;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type RemovePeerData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}/peer';
};

export type RemovePeerErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * No active peers found
     */
    404: ApiError;
};

export type RemovePeerError = RemovePeerErrors[keyof RemovePeerErrors];

export type RemovePeerResponses = {
    /**
     * Peers removed
     */
    200: unknown;
};

export type DeleteSubscriptionData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}/subscription';
};

export type DeleteSubscriptionErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * No active subscription found
     */
    404: ApiError;
};

export type DeleteSubscriptionError = DeleteSubscriptionErrors[keyof DeleteSubscriptionErrors];

export type DeleteSubscriptionResponses = {
    /**
     * Subscription deleted
     */
    200: unknown;
};

export type SetSubscriptionData = {
    body: SetSubscriptionRequest;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}/subscription';
};

export type SetSubscriptionErrors = {
    /**
     * Days not specified and plan has no trial_days
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * Plan not found
     */
    404: ApiError;
    /**
     * Internal server error
     */
    500: ApiError;
};

export type SetSubscriptionError = SetSubscriptionErrors[keyof SetSubscriptionErrors];

export type SetSubscriptionResponses = {
    /**
     * Subscription set
     */
    200: unknown;
};

export type RegenerateAdminVlessConfigData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: number;
    };
    query?: never;
    url: '/users/{id}/vless-config/regenerate';
};

export type RegenerateAdminVlessConfigErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
    /**
     * User not found or has no VLESS config
     */
    404: ApiError;
};

export type RegenerateAdminVlessConfigError = RegenerateAdminVlessConfigErrors[keyof RegenerateAdminVlessConfigErrors];

export type RegenerateAdminVlessConfigResponses = {
    /**
     * VLESS config regenerated
     */
    200: unknown;
};

export type GetVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/version';
};

export type GetVersionResponses = {
    200: VersionInfo;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type ListVlessPeersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/vless-peers';
};

export type ListVlessPeersErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Not an admin
     */
    403: ApiError;
};

export type ListVlessPeersError = ListVlessPeersErrors[keyof ListVlessPeersErrors];

export type ListVlessPeersResponses = {
    200: Array<VlessPeerSummary>;
};

export type ListVlessPeersResponse = ListVlessPeersResponses[keyof ListVlessPeersResponses];
